#!/bin/sh
rm -f  *.fls *.ilg *.ind *.fdb_latexmk *converted* *.4ct *.4tc *.aux *.css *.dvi *.idv *.idx *.lg *.log *.tmp *.toc *.out *.xref *.svg comment.cut kindlemlbook*.png pandocfiguresmlbook*.png *.hi *.o *.cpt foo pandocmlbook.pdf
make clean
