#!/bin/bash
ebook-convert kindlemlbook2.html kindlemlbook2.mobi --output-profile kindle --disable-font-rescaling --author-sort "Whitington,John" --authors "John Whitington" --publisher "Coherent Press" --title "More OCaml: Algorithms, Methods & Diversions" --no-inline-toc

