#!/bin/bash
/Applications/calibre.app/Contents/MacOS/ebook-convert kindlemlbook.html kindlemlbook.mobi --output-profile kindle --disable-font-rescaling --author-sort "Whitington,John" --authors "John Whitington" --publisher "Coherent Press" --title "OCaml from the Very Beginning" --no-inline-toc

